[package]
name = "siox"
version = "0.1.0"
edition = "2021"
rust-version = "1.90"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Siox-lang/sioxc"
authors = ["siox contributors"]
description = "The siox compiler"

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
inkwell = { version = "0.9.0", optional = true, default-features = false, features = ["llvm22-1", "target-x86"] }

[features]
default = ["cli"]
cli = ["dep:clap", "llvm"]
llvm = ["dep:inkwell"]
simd = []
wide = []
f128 = []
bitpack = []

[lib]
name = "siox"
path = "src/lib.rs"

[[bin]]
name = "sioxc"
path = "src/main.rs"
required-features = ["cli"]

[profile.release]
lto = "thin"
