//! Build a compiled design into a simulator cocotb can drive.
//!
//! cocotb is not linked against a simulator; it is the other way round. cocotb
//! ships `libcocotbvpi_*.so`, which registers itself through
//! `vlog_startup_routines_bootstrap` and then calls back into the `vpi_*`
//! symbols the *simulator* exports. So the artifact here is an executable that
//! owns the time loop and answers those calls, with the design linked in
//! behind its `sx_*` ABI.
//!
//! Everything cocotb-specific is discovered by running `cocotb-config`, which
//! is installed alongside cocotb itself. That keeps the compiler free of any
//! hard-coded paths into a Python environment, and means a virtualenv works
//! without configuration as long as its `bin` is on `PATH`.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::Command;

use siox::elab::Hierarchy;
use siox::ir::Design;
use siox::syntax::ast;
use siox::syntax::ast::Module;

/// The VPI implementation and its header, embedded so a built `sioxc` needs no
/// data files beside it.
const VPI_C: &str = include_str!("cocotb_vpi.c");
const VPI_H: &str = include_str!("vpi_user.h");

/// Where cocotb lives, as `cocotb-config` reports it.
struct Cocotb {
    /// The VPI library whose startup routine boots the Python side.
    vpi_lib: PathBuf,
    /// Directory holding it and its `libgpi`/`libcocotb` dependencies.
    lib_dir: PathBuf,
    /// The interpreter cocotb was installed into; baked in so the simulator
    /// runs without `PYGPI_PYTHON_BIN` having to be set by hand.
    python: String,
}

fn config(args: &[&str]) -> Result<String, String> {
    let program = std::env::var("SIOX_COCOTB_CONFIG").unwrap_or_else(|_| "cocotb-config".into());
    let out = Command::new(&program).args(args).output().map_err(|e| {
        format!(
            "could not run `{program}`: {e}\n\
             cocotb provides it; install cocotb (`pip install cocotb`) or point \
             SIOX_COCOTB_CONFIG at its `cocotb-config`"
        )
    })?;
    if !out.status.success() {
        return Err(format!(
            "`{program} {}` failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn find_cocotb() -> Result<Cocotb, String> {
    // Any of cocotb's VPI libraries will do: they differ in name so that a
    // simulator can pick "its" one, not in what they require of us. Verilator's
    // is the one built for a simulator that is not a Verilog interpreter, which
    // is exactly the position siox is in.
    let vpi_lib = PathBuf::from(config(&["--lib-name-path", "vpi", "verilator"])?);
    if !vpi_lib.exists() {
        return Err(format!(
            "cocotb reported its VPI library as {} but it is not there",
            vpi_lib.display()
        ));
    }
    Ok(Cocotb {
        lib_dir: PathBuf::from(config(&["--lib-dir"])?),
        python: config(&["--python-bin"])?,
        vpi_lib,
    })
}

fn c_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Ports of the design's root entity, by name, with their direction. Signal
/// records carry no direction of their own -- it is a property of the port
/// declaration -- so it is recovered here and handed to the VPI layer, which
/// reports it for `vpiDirection`.
fn root_port_directions(
    modules: &[Module],
    hier: &Hierarchy,
    root: siox::elab::InstanceId,
) -> Vec<(String, ast::Direction)> {
    let entity = &hier.instance(root).entity;
    modules
        .iter()
        .flat_map(|m| &m.items)
        .find_map(|item| match item {
            ast::Item::Entity(e) if &e.name.text == entity => Some(
                e.ports
                    .iter()
                    .map(|p| (p.name.text.clone(), p.dir.unwrap_or(ast::Direction::In)))
                    .collect(),
            ),
            _ => None,
        })
        .unwrap_or_default()
}

/// The C table the VPI layer reads: one row per signal, in `SignalId` order so
/// the index *is* the argument `sx_read`/`sx_set` take.
fn signal_table(design: &Design, top: &str, ports: &[(String, ast::Direction)]) -> String {
    let inputs: BTreeSet<&str> = ports
        .iter()
        .filter(|(_, d)| matches!(d, ast::Direction::In | ast::Direction::Inout))
        .map(|(n, _)| n.as_str())
        .collect();
    let mut out = String::from(
        "/* Generated by sioxc: the design's signals, indexed by SignalId. */\n\
         #include <stddef.h>\n\n\
         typedef struct {\n\
         \x20   const char *path;\n\
         \x20   unsigned width;\n\
         \x20   unsigned char is_input;\n\
         } sx_vpi_signal;\n\n\
         const sx_vpi_signal sx_vpi_signals[] = {\n",
    );
    for signal in &design.signals {
        // Only a port of the root is drivable from outside; an internal signal
        // is reported as an output so cocotb reads rather than drives it.
        let leaf = signal.path.rsplit('.').next().unwrap_or(&signal.path);
        let depth = signal.path.matches('.').count();
        let is_input = depth == 1 && inputs.contains(leaf);
        out.push_str(&format!(
            "    {{ \"{}\", {}, {} }},\n",
            c_escape(&signal.path),
            signal.width,
            u8::from(is_input),
        ));
    }
    out.push_str("};\n");
    out.push_str(&format!(
        "const unsigned sx_vpi_signal_count = {};\n",
        design.signals.len()
    ));
    out.push_str(&format!(
        "const char *const sx_vpi_top = \"{}\";\n",
        c_escape(top)
    ));
    out
}

/// Compile `design` into an executable cocotb can drive.
pub fn build(
    modules: &[Module],
    hier: &Hierarchy,
    design: &Design,
    out: &Path,
) -> Result<(), String> {
    let issues = design.validate();
    if !issues.is_empty() {
        return Err(format!(
            "cannot generate native code:\n  - {}",
            issues.join("\n  - ")
        ));
    }
    let root = *hier
        .roots
        .first()
        .ok_or("no top entity was elaborated to build a cocotb simulator from")?;
    let cocotb = find_cocotb()?;

    let dir = out
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));
    let stem = out
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_else(|| "sim".into());
    let work = dir.join(format!(".{stem}.cocotb"));
    std::fs::create_dir_all(&work).map_err(|e| e.to_string())?;

    let obj = work.join("design.o");
    siox::llvm::emit_object(design, &obj)?;

    let top = hier.root_path(root);
    let ports = root_port_directions(modules, hier, root);
    std::fs::write(work.join("vpi_user.h"), VPI_H).map_err(|e| e.to_string())?;
    std::fs::write(work.join("sx_vpi.c"), VPI_C).map_err(|e| e.to_string())?;
    std::fs::write(
        work.join("sx_signals.c"),
        signal_table(design, &top, &ports),
    )
    .map_err(|e| e.to_string())?;

    let status = Command::new("clang")
        .arg("-O1")
        .arg("-o")
        .arg(out)
        .arg(work.join("sx_vpi.c"))
        .arg(work.join("sx_signals.c"))
        .arg(&obj)
        .arg(format!("-I{}", work.display()))
        // The product string cocotb prints is the *simulator*, so it is
        // siox's version, not cocotb's. The cocotb version is only checked.
        .arg(format!(
            "-DSX_VPI_VERSION=\"{}\"",
            env!("CARGO_PKG_VERSION")
        ))
        .arg(format!("-DSX_PYGPI_PYTHON_BIN=\"{}\"", cocotb.python))
        .arg(&cocotb.vpi_lib)
        .arg(format!("-Wl,-rpath,{}", cocotb.lib_dir.display()))
        // cocotb's library calls back into the `vpi_*` symbols defined in the
        // executable, so they have to be in its dynamic symbol table.
        .arg("-Wl,--export-dynamic")
        .status()
        .map_err(|e| format!("could not run clang: {e}"))?;
    if !status.success() {
        return Err("clang failed to link the cocotb simulator".into());
    }
    Ok(())
}
