//! Direct LLVM support for the canonical process representation.
//!
//! The first part of the generated-C replacement is the source-independent
//! metadata boundary: a linked runtime must discover tests and scheduled
//! processes from the design object, not from a C file generated by the
//! compiler. Execution entry points are added beside these tables as the
//! Process IR emitter gains instruction coverage.

use std::collections::HashMap;

use inkwell::builder::Builder;
use inkwell::context::Context;
use inkwell::module::{Linkage, Module};
use inkwell::values::{FunctionValue, IntValue, PointerValue};
use inkwell::AddressSpace;
use inkwell::IntPredicate;

use siox::ir::{
    Design, ProcessActivation, ProcessBinaryOp, ProcessCfg, ProcessNumber, ProcessSensitivity,
    ProcessSignalState, ProcessTerminator, ProcessUnaryOp, ProcessValueId, ProcessValueKind,
    SignalId,
};

/// Version of the native process metadata ABI emitted into every object.
///
/// This is deliberately a data version rather than the compiler package
/// version: the reusable native runtime only needs to change when one of the
/// exported table layouts or encodings changes.
const PROCESS_ABI_VERSION: u32 = 3;

/// A process returned normally and has no pending resume.
const PROCESS_COMPLETED: u8 = 0;
/// The process stopped itself while leaving the simulation alive.
const PROCESS_STOPPED: u8 = 2;
/// The process requested termination of the complete simulation.
const PROCESS_FINISHED: u8 = 3;
/// This migration build encountered an instruction/terminator whose direct
/// lowering is not implemented yet. The runtime must report this, never treat
/// it as successful completion.
const PROCESS_UNSUPPORTED: u8 = u8::MAX;

/// Convert an integer to another exact LLVM width without changing its
/// unsigned bit pattern.
fn fit<'ctx>(builder: &Builder<'ctx>, value: IntValue<'ctx>, width: u32) -> Option<IntValue<'ctx>> {
    let ty = value
        .get_type()
        .get_context()
        .custom_width_int_type(std::num::NonZeroU32::new(width)?)
        .ok()?;
    match value.get_type().get_bit_width().cmp(&width) {
        std::cmp::Ordering::Less => builder.build_int_z_extend(value, ty, "pv.zx").ok(),
        std::cmp::Ordering::Greater => builder.build_int_truncate(value, ty, "pv.tr").ok(),
        std::cmp::Ordering::Equal => Some(value),
    }
}

/// Signed counterpart of [`fit`].
fn fit_signed<'ctx>(
    builder: &Builder<'ctx>,
    value: IntValue<'ctx>,
    width: u32,
) -> Option<IntValue<'ctx>> {
    let ty = value
        .get_type()
        .get_context()
        .custom_width_int_type(std::num::NonZeroU32::new(width)?)
        .ok()?;
    match value.get_type().get_bit_width().cmp(&width) {
        std::cmp::Ordering::Less => builder.build_int_s_extend(value, ty, "pv.sx").ok(),
        std::cmp::Ordering::Greater => builder.build_int_truncate(value, ty, "pv.tr").ok(),
        std::cmp::Ordering::Equal => Some(value),
    }
}

/// Read one scalar signal value through a word accessor and reconstruct its
/// exact LLVM integer. The current plane uses the stable design ABI; old/event
/// accessors remain internal to the emitted design object.
fn signal_value<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    builder: &Builder<'ctx>,
    design: &Design,
    signals: &[siox::ir::SignalId],
    state: ProcessSignalState,
    width: u32,
) -> Option<IntValue<'ctx>> {
    let [signal] = signals else {
        return None;
    };
    let signal_width = match state {
        ProcessSignalState::Current | ProcessSignalState::Old => design.signal_width(*signal)?,
        ProcessSignalState::Event => 1,
    };
    let value_type = context
        .custom_width_int_type(std::num::NonZeroU32::new(width)?)
        .ok()?;
    let read = module.get_function(match state {
        ProcessSignalState::Current => "sx_read_word",
        ProcessSignalState::Old => "sx.process.read.old",
        ProcessSignalState::Event => "sx.process.read.event",
    })?;
    let mut value = value_type.const_zero();
    // Never request or shift a word whose first bit lies outside the result.
    // A malformed hand-built IR can disagree with the signal width; treating
    // the result width as the cap keeps that mismatch from producing LLVM
    // shift poison before validation grows a stronger shape check.
    for word in 0..super::words_for(signal_width.min(width)) {
        let call = builder
            .build_call(
                read,
                &[
                    context
                        .i32_type()
                        .const_int(u64::from(signal.0), false)
                        .into(),
                    context.i32_type().const_int(u64::from(word), false).into(),
                ],
                "pv.word",
            )
            .ok()?
            .try_as_basic_value();
        let raw = match call {
            inkwell::values::ValueKind::Basic(value) => value.into_int_value(),
            _ => return None,
        };
        let placed = fit(builder, raw, width)?;
        let offset = word.checked_mul(super::ABI_WORD_BITS)?;
        let placed = if offset == 0 {
            placed
        } else {
            builder
                .build_left_shift(
                    placed,
                    value_type.const_int(u64::from(offset), false),
                    "pv.place",
                )
                .ok()?
        };
        value = builder.build_or(value, placed, "pv.join").ok()?;
    }
    Some(value)
}

/// Emit an arena value and convert it to the operation's contextual width.
#[allow(clippy::too_many_arguments)]
fn process_value_at<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    builder: &Builder<'ctx>,
    design: &Design,
    id: ProcessValueId,
    width: u32,
    signed: bool,
    cache: &mut HashMap<ProcessValueId, IntValue<'ctx>>,
) -> Option<IntValue<'ctx>> {
    let value = process_value(context, module, builder, design, id, cache)?;
    if signed && process_value_is_signed(design, id) {
        fit_signed(builder, value, width)
    } else {
        fit(builder, value, width)
    }
}

/// Whether a scalar arena value denotes a signed mathematical result rather
/// than merely carrying a bit pattern whose high bit happens to be set.
///
/// This distinction matters when a signed operation widens an operand. The
/// minimum representation of the positive literal `3` is `i2 3`, but it must
/// zero-extend to `i65 3`; blindly sign-extending it would turn it into `-1`.
/// Conversely, a negative-capable kernel-integer signal and the result of a
/// signed arithmetic operation must preserve their sign. This mirrors the
/// established digital emitter's contextual signed-operand rules.
fn process_value_is_signed(design: &Design, id: ProcessValueId) -> bool {
    let Some(value) = design.process_ir.values.get(id.0 as usize) else {
        return false;
    };
    match &value.kind {
        ProcessValueKind::Signal { signals, state } => {
            let [signal] = signals.as_slice() else {
                return false;
            };
            !matches!(state, ProcessSignalState::Event)
                && design.signals.get(signal.0 as usize).is_some_and(|signal| {
                    signal.integer && signal.range.map(|(left, _)| left < 0).unwrap_or(true)
                })
        }
        ProcessValueKind::Local { .. } | ProcessValueKind::Storage(_) => {
            matches!(value.ty, Some(siox::types::Ty::Integer))
        }
        ProcessValueKind::Unary { operation, .. } => matches!(
            operation,
            ProcessUnaryOp::Neg | ProcessUnaryOp::RealToInteger
        ),
        ProcessValueKind::Binary { operation, .. } => matches!(
            operation,
            ProcessBinaryOp::SignedAdd
                | ProcessBinaryOp::SignedSub
                | ProcessBinaryOp::SignedMul
                | ProcessBinaryOp::SignedDiv
                | ProcessBinaryOp::ArithmeticShr
        ),
        ProcessValueKind::Select {
            then_value,
            else_value,
            ..
        } => {
            process_value_is_signed(design, *then_value)
                || process_value_is_signed(design, *else_value)
        }
        ProcessValueKind::ForeignCall { integer_result, .. } => *integer_result,
        _ => false,
    }
}

/// Convert an arbitrary-width scalar to the one-bit condition domain.
fn as_condition<'ctx>(builder: &Builder<'ctx>, value: IntValue<'ctx>) -> Option<IntValue<'ctx>> {
    if value.get_type().get_bit_width() == 1 {
        Some(value)
    } else {
        builder
            .build_int_compare(
                IntPredicate::NE,
                value,
                value.get_type().const_zero(),
                "pv.condition",
            )
            .ok()
    }
}

/// Emit a normalized scalar binary operation with the same defined corner
/// cases as the established hardware LLVM path.
#[allow(clippy::too_many_arguments)]
fn process_binary<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    builder: &Builder<'ctx>,
    design: &Design,
    operation: &ProcessBinaryOp,
    left: ProcessValueId,
    right: ProcessValueId,
    result_width: u32,
    cache: &mut HashMap<ProcessValueId, IntValue<'ctx>>,
) -> Option<IntValue<'ctx>> {
    let left_width = design.process_ir.values.get(left.0 as usize)?.bit_width?;
    let right_width = design.process_ir.values.get(right.0 as usize)?.bit_width?;

    if matches!(
        operation,
        ProcessBinaryOp::FloatAdd
            | ProcessBinaryOp::FloatSub
            | ProcessBinaryOp::FloatMul
            | ProcessBinaryOp::FloatDiv
    ) {
        let float = context.f64_type();
        let left = process_value_at(context, module, builder, design, left, 64, false, cache)?;
        let right = process_value_at(context, module, builder, design, right, 64, false, cache)?;
        let left = builder
            .build_bit_cast(left, float, "pv.fa")
            .ok()?
            .into_float_value();
        let right = builder
            .build_bit_cast(right, float, "pv.fb")
            .ok()?
            .into_float_value();
        let result = match operation {
            ProcessBinaryOp::FloatAdd => builder.build_float_add(left, right, "pv.fadd").ok()?,
            ProcessBinaryOp::FloatSub => builder.build_float_sub(left, right, "pv.fsub").ok()?,
            ProcessBinaryOp::FloatMul => builder.build_float_mul(left, right, "pv.fmul").ok()?,
            ProcessBinaryOp::FloatDiv => builder.build_float_div(left, right, "pv.fdiv").ok()?,
            _ => return None,
        };
        let bits = builder
            .build_bit_cast(result, context.i64_type(), "pv.fbits")
            .ok()?
            .into_int_value();
        return fit(builder, bits, result_width);
    }

    if matches!(
        operation,
        ProcessBinaryOp::FloatEq
            | ProcessBinaryOp::FloatNe
            | ProcessBinaryOp::FloatLt
            | ProcessBinaryOp::FloatLe
            | ProcessBinaryOp::FloatGt
            | ProcessBinaryOp::FloatGe
    ) {
        let float = context.f64_type();
        let left = process_value_at(context, module, builder, design, left, 64, false, cache)?;
        let right = process_value_at(context, module, builder, design, right, 64, false, cache)?;
        let left = builder
            .build_bit_cast(left, float, "pv.fa")
            .ok()?
            .into_float_value();
        let right = builder
            .build_bit_cast(right, float, "pv.fb")
            .ok()?
            .into_float_value();
        let predicate = match operation {
            ProcessBinaryOp::FloatEq => inkwell::FloatPredicate::OEQ,
            ProcessBinaryOp::FloatNe => inkwell::FloatPredicate::UNE,
            ProcessBinaryOp::FloatLt => inkwell::FloatPredicate::OLT,
            ProcessBinaryOp::FloatLe => inkwell::FloatPredicate::OLE,
            ProcessBinaryOp::FloatGt => inkwell::FloatPredicate::OGT,
            ProcessBinaryOp::FloatGe => inkwell::FloatPredicate::OGE,
            _ => return None,
        };
        let result = builder
            .build_float_compare(predicate, left, right, "pv.fcmp")
            .ok()?;
        return fit(builder, result, result_width);
    }

    let comparison = matches!(
        operation,
        ProcessBinaryOp::Eq
            | ProcessBinaryOp::Ne
            | ProcessBinaryOp::Lt
            | ProcessBinaryOp::Le
            | ProcessBinaryOp::Gt
            | ProcessBinaryOp::Ge
            | ProcessBinaryOp::SignedLt
            | ProcessBinaryOp::SignedLe
            | ProcessBinaryOp::SignedGt
            | ProcessBinaryOp::SignedGe
    );
    let signed = matches!(
        operation,
        ProcessBinaryOp::SignedAdd
            | ProcessBinaryOp::SignedSub
            | ProcessBinaryOp::SignedMul
            | ProcessBinaryOp::SignedDiv
            | ProcessBinaryOp::SignedLt
            | ProcessBinaryOp::SignedLe
            | ProcessBinaryOp::SignedGt
            | ProcessBinaryOp::SignedGe
            | ProcessBinaryOp::ArithmeticShr
    );
    let operand_width = if comparison {
        left_width.max(right_width)
    } else {
        result_width
    };
    let operand_width = if signed {
        operand_width.checked_add(1)?
    } else {
        operand_width
    };
    if operand_width > super::emit::LLVM_MAX_INT_BITS {
        return None;
    }

    if matches!(
        operation,
        ProcessBinaryOp::Shl | ProcessBinaryOp::Shr | ProcessBinaryOp::ArithmeticShr
    ) {
        let shift_width = operand_width.max(right_width);
        let left = process_value_at(
            context,
            module,
            builder,
            design,
            left,
            shift_width,
            matches!(operation, ProcessBinaryOp::ArithmeticShr),
            cache,
        )?;
        let right = process_value_at(
            context,
            module,
            builder,
            design,
            right,
            shift_width,
            false,
            cache,
        )?;
        let ty = left.get_type();
        let limit = ty.const_int(u64::from(operand_width), false);
        let out_of_range = builder
            .build_int_compare(IntPredicate::UGE, right, limit, "pv.shift.oob")
            .ok()?;
        let zero = ty.const_zero();
        let safe = builder
            .build_select(out_of_range, zero, right, "pv.shift.amount")
            .ok()?
            .into_int_value();
        let shifted = if matches!(operation, ProcessBinaryOp::Shl) {
            builder.build_left_shift(left, safe, "pv.shl").ok()?
        } else {
            builder
                .build_right_shift(
                    left,
                    safe,
                    matches!(operation, ProcessBinaryOp::ArithmeticShr),
                    "pv.shr",
                )
                .ok()?
        };
        let out_of_range_value = if matches!(operation, ProcessBinaryOp::ArithmeticShr) {
            let negative = builder
                .build_int_compare(IntPredicate::SLT, left, zero, "pv.shift.negative")
                .ok()?;
            builder
                .build_select(negative, ty.const_all_ones(), zero, "pv.shift.fill")
                .ok()?
                .into_int_value()
        } else {
            zero
        };
        let result = builder
            .build_select(out_of_range, out_of_range_value, shifted, "pv.shift.result")
            .ok()?
            .into_int_value();
        return fit(builder, result, result_width);
    }

    let left = process_value_at(
        context,
        module,
        builder,
        design,
        left,
        operand_width,
        signed,
        cache,
    )?;
    let right = process_value_at(
        context,
        module,
        builder,
        design,
        right,
        operand_width,
        signed,
        cache,
    )?;
    let compare = |predicate, name| {
        let value = builder
            .build_int_compare(predicate, left, right, name)
            .ok()?;
        fit(builder, value, result_width)
    };
    let result = match operation {
        ProcessBinaryOp::Add | ProcessBinaryOp::SignedAdd => {
            builder.build_int_add(left, right, "pv.add").ok()?
        }
        ProcessBinaryOp::Sub | ProcessBinaryOp::SignedSub => {
            builder.build_int_sub(left, right, "pv.sub").ok()?
        }
        ProcessBinaryOp::Mul | ProcessBinaryOp::SignedMul => {
            builder.build_int_mul(left, right, "pv.mul").ok()?
        }
        ProcessBinaryOp::Div => {
            let zero = left.get_type().const_zero();
            let one = left.get_type().const_int(1, false);
            let is_zero = builder
                .build_int_compare(IntPredicate::EQ, right, zero, "pv.div.zero")
                .ok()?;
            let safe = builder
                .build_select(is_zero, one, right, "pv.div.denominator")
                .ok()?
                .into_int_value();
            let quotient = builder.build_int_unsigned_div(left, safe, "pv.div").ok()?;
            builder
                .build_select(is_zero, zero, quotient, "pv.div.result")
                .ok()?
                .into_int_value()
        }
        ProcessBinaryOp::SignedDiv => {
            let ty = left.get_type();
            let zero = ty.const_zero();
            let one = ty.const_int(1, false);
            let negative_one = ty.const_all_ones();
            let minimum = builder
                .build_left_shift(
                    one,
                    ty.const_int(u64::from(operand_width - 1), false),
                    "pv.sdiv.minimum",
                )
                .ok()?;
            let is_zero = builder
                .build_int_compare(IntPredicate::EQ, right, zero, "pv.sdiv.zero")
                .ok()?;
            let is_minimum = builder
                .build_int_compare(IntPredicate::EQ, left, minimum, "pv.sdiv.is_minimum")
                .ok()?;
            let is_negative_one = builder
                .build_int_compare(
                    IntPredicate::EQ,
                    right,
                    negative_one,
                    "pv.sdiv.is_negative_one",
                )
                .ok()?;
            let overflow = builder
                .build_and(is_minimum, is_negative_one, "pv.sdiv.overflow")
                .ok()?;
            let unsafe_divisor = builder.build_or(is_zero, overflow, "pv.sdiv.unsafe").ok()?;
            let safe = builder
                .build_select(unsafe_divisor, one, right, "pv.sdiv.denominator")
                .ok()?
                .into_int_value();
            let quotient = builder.build_int_signed_div(left, safe, "pv.sdiv").ok()?;
            let quotient = builder
                .build_select(overflow, minimum, quotient, "pv.sdiv.overflow.result")
                .ok()?
                .into_int_value();
            builder
                .build_select(is_zero, zero, quotient, "pv.sdiv.result")
                .ok()?
                .into_int_value()
        }
        ProcessBinaryOp::And => builder.build_and(left, right, "pv.and").ok()?,
        ProcessBinaryOp::Or => builder.build_or(left, right, "pv.or").ok()?,
        ProcessBinaryOp::Xor => builder.build_xor(left, right, "pv.xor").ok()?,
        ProcessBinaryOp::Eq => return compare(IntPredicate::EQ, "pv.eq"),
        ProcessBinaryOp::Ne => return compare(IntPredicate::NE, "pv.ne"),
        ProcessBinaryOp::Lt => return compare(IntPredicate::ULT, "pv.lt"),
        ProcessBinaryOp::Le => return compare(IntPredicate::ULE, "pv.le"),
        ProcessBinaryOp::Gt => return compare(IntPredicate::UGT, "pv.gt"),
        ProcessBinaryOp::Ge => return compare(IntPredicate::UGE, "pv.ge"),
        ProcessBinaryOp::SignedLt => return compare(IntPredicate::SLT, "pv.slt"),
        ProcessBinaryOp::SignedLe => return compare(IntPredicate::SLE, "pv.sle"),
        ProcessBinaryOp::SignedGt => return compare(IntPredicate::SGT, "pv.sgt"),
        ProcessBinaryOp::SignedGe => return compare(IntPredicate::SGE, "pv.sge"),
        ProcessBinaryOp::Shl
        | ProcessBinaryOp::Shr
        | ProcessBinaryOp::ArithmeticShr
        | ProcessBinaryOp::FloatAdd
        | ProcessBinaryOp::FloatSub
        | ProcessBinaryOp::FloatMul
        | ProcessBinaryOp::FloatDiv
        | ProcessBinaryOp::FloatEq
        | ProcessBinaryOp::FloatNe
        | ProcessBinaryOp::FloatLt
        | ProcessBinaryOp::FloatLe
        | ProcessBinaryOp::FloatGt
        | ProcessBinaryOp::FloatGe
        | ProcessBinaryOp::Custom(_) => return None,
    };
    fit(builder, result, result_width)
}

/// Emit the scalar subset needed by direct CFG control. Values are dependency
/// ordered, but the per-block cache also prevents a shared arena node from
/// being emitted more than once in one LLVM block. Foreign calls invalidate
/// cached signal reads because they may mutate state through the public ABI.
fn process_value<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    builder: &Builder<'ctx>,
    design: &Design,
    id: ProcessValueId,
    cache: &mut HashMap<ProcessValueId, IntValue<'ctx>>,
) -> Option<IntValue<'ctx>> {
    if let Some(value) = cache.get(&id).copied() {
        return Some(value);
    }
    let value = design.process_ir.values.get(id.0 as usize)?;
    let width = value.bit_width?;
    if width > super::emit::LLVM_MAX_INT_BITS {
        return None;
    }
    let ty = context
        .custom_width_int_type(std::num::NonZeroU32::new(width)?)
        .ok()?;
    let emitted = match &value.kind {
        ProcessValueKind::Number(ProcessNumber::Integer(words))
        | ProcessValueKind::BitString { words, .. } => ty.const_int_arbitrary_precision(words),
        ProcessValueKind::Number(ProcessNumber::Real(bits)) => ty.const_int(*bits, false),
        ProcessValueKind::Char(character) => ty.const_int(u64::from(u32::from(*character)), false),
        ProcessValueKind::Signal { signals, state } => {
            signal_value(context, module, builder, design, signals, *state, width)?
        }
        ProcessValueKind::BitSlice { base, high, low } => {
            let base = process_value(context, module, builder, design, *base, cache)?;
            let base_width = base.get_type().get_bit_width();
            if high < low || *high >= base_width {
                return None;
            }
            let shifted = if *low == 0 {
                base
            } else {
                builder
                    .build_right_shift(
                        base,
                        base.get_type().const_int(u64::from(*low), false),
                        false,
                        "pv.slice",
                    )
                    .ok()?
            };
            fit(builder, shifted, width)?
        }
        ProcessValueKind::TableLookup { table, index } => {
            let metadata = design.lookup_tables.get(table.0)?;
            let count = u64::try_from(metadata.values.len()).ok()?;
            let count_width = (64 - count.leading_zeros()).max(1);
            let index_width = design
                .process_ir
                .values
                .get(index.0 as usize)?
                .bit_width?
                .max(count_width);
            let index = process_value_at(
                context,
                module,
                builder,
                design,
                *index,
                index_width,
                false,
                cache,
            )?;
            let in_range = builder
                .build_int_compare(
                    IntPredicate::ULT,
                    index,
                    index.get_type().const_int(count, false),
                    "pv.table.in_range",
                )
                .ok()?;
            let safe_index = builder
                .build_select(
                    in_range,
                    index,
                    index.get_type().const_zero(),
                    "pv.table.safe_index",
                )
                .ok()?
                .into_int_value();
            let safe_index = fit(builder, safe_index, 64)?;
            let storage_width = metadata.element_width.next_power_of_two().max(8);
            let storage = context
                .custom_width_int_type(std::num::NonZeroU32::new(storage_width)?)
                .ok()?;
            let array = storage.array_type(u32::try_from(metadata.values.len()).ok()?);
            let global = module.get_global(&format!("sx.lookup.{}", table.0))?;
            let pointer = unsafe {
                builder
                    .build_in_bounds_gep(
                        array,
                        global.as_pointer_value(),
                        &[context.i64_type().const_zero(), safe_index],
                        "pv.table.pointer",
                    )
                    .ok()?
            };
            let loaded = builder
                .build_load(storage, pointer, "pv.table.value")
                .ok()?
                .into_int_value();
            let selected = builder
                .build_select(in_range, loaded, storage.const_zero(), "pv.table.result")
                .ok()?
                .into_int_value();
            fit(builder, selected, width)?
        }
        ProcessValueKind::ForeignCall {
            name,
            arguments,
            float_arguments,
            integer_arguments,
            float_result,
            integer_result,
        } => {
            use inkwell::types::BasicMetadataTypeEnum as MetadataType;
            use inkwell::values::BasicMetadataValueEnum as MetadataValue;

            let float = context.f64_type();
            let mut parameter_types = Vec::<MetadataType>::with_capacity(arguments.len());
            let mut argument_values = Vec::<MetadataValue>::with_capacity(arguments.len());
            for (index, argument) in arguments.iter().enumerate() {
                let argument = process_value_at(
                    context,
                    module,
                    builder,
                    design,
                    *argument,
                    64,
                    integer_arguments.get(index).copied().unwrap_or(false),
                    cache,
                )?;
                if float_arguments.get(index).copied().unwrap_or(false) {
                    parameter_types.push(float.into());
                    argument_values.push(
                        builder
                            .build_bit_cast(argument, float, "pv.foreign.float_argument")
                            .ok()?
                            .into_float_value()
                            .into(),
                    );
                } else {
                    parameter_types.push(context.i64_type().into());
                    argument_values.push(argument.into());
                }
            }
            let function = module.get_function(name).unwrap_or_else(|| {
                let signature = if *float_result {
                    float.fn_type(&parameter_types, false)
                } else {
                    context.i64_type().fn_type(&parameter_types, false)
                };
                module.add_function(name, signature, Some(Linkage::External))
            });
            let returned = match builder
                .build_call(function, &argument_values, "pv.foreign")
                .ok()?
                .try_as_basic_value()
            {
                inkwell::values::ValueKind::Basic(value) => value,
                _ => return None,
            };
            // Foreign code may call public signal accessors. Later arena reads
            // must observe that mutation rather than reuse an earlier load.
            cache.clear();
            let returned = if *float_result {
                builder
                    .build_bit_cast(
                        returned.into_float_value(),
                        context.i64_type(),
                        "pv.foreign.float_result",
                    )
                    .ok()?
                    .into_int_value()
            } else {
                returned.into_int_value()
            };
            if *integer_result {
                fit_signed(builder, returned, width)?
            } else {
                fit(builder, returned, width)?
            }
        }
        ProcessValueKind::Unary { operation, operand } => match operation {
            ProcessUnaryOp::Neg => {
                let operand = process_value_at(
                    context, module, builder, design, *operand, width, false, cache,
                )?;
                builder.build_int_neg(operand, "pv.neg").ok()?
            }
            ProcessUnaryOp::Not => {
                let operand = process_value(context, module, builder, design, *operand, cache)?;
                let inverted = builder
                    .build_int_compare(
                        IntPredicate::EQ,
                        operand,
                        operand.get_type().const_zero(),
                        "pv.not",
                    )
                    .ok()?;
                fit(builder, inverted, width)?
            }
            ProcessUnaryOp::RealToInteger => {
                let operand =
                    process_value_at(context, module, builder, design, *operand, 64, false, cache)?;
                let real = builder
                    .build_bit_cast(operand, context.f64_type(), "pv.real.bits")
                    .ok()?
                    .into_float_value();
                let integer = builder
                    .build_float_to_signed_int(real, context.i64_type(), "pv.real.integer")
                    .ok()?;
                fit_signed(builder, integer, width)?
            }
        },
        ProcessValueKind::Binary {
            operation,
            left,
            right,
        } => process_binary(
            context, module, builder, design, operation, *left, *right, width, cache,
        )?,
        ProcessValueKind::Select {
            condition: selected,
            then_value,
            else_value,
        } => {
            let selected = process_value(context, module, builder, design, *selected, cache)?;
            let selected = as_condition(builder, selected)?;
            let then_value = process_value_at(
                context,
                module,
                builder,
                design,
                *then_value,
                width,
                false,
                cache,
            )?;
            let else_value = process_value_at(
                context,
                module,
                builder,
                design,
                *else_value,
                width,
                false,
                cache,
            )?;
            builder
                .build_select(selected, then_value, else_value, "pv.select")
                .ok()?
                .into_int_value()
        }
        ProcessValueKind::Concat(parts) => {
            let mut joined = ty.const_zero();
            let mut offset = width;
            for part in parts {
                let part_width = design.process_ir.values.get(part.0 as usize)?.bit_width?;
                offset = offset.checked_sub(part_width)?;
                let part =
                    process_value_at(context, module, builder, design, *part, width, false, cache)?;
                let part = if offset == 0 {
                    part
                } else {
                    builder
                        .build_left_shift(
                            part,
                            ty.const_int(u64::from(offset), false),
                            "pv.concat.place",
                        )
                        .ok()?
                };
                joined = builder.build_or(joined, part, "pv.concat").ok()?;
            }
            if offset != 0 {
                return None;
            }
            joined
        }
        _ => return None,
    };
    cache.insert(id, emitted);
    Some(emitted)
}

/// Emit one externally visible, immutable `u32` value.
fn u32_global<'ctx>(context: &'ctx Context, module: &Module<'ctx>, name: &str, value: u32) {
    let ty = context.i32_type();
    let global = module.add_global(ty, None, name);
    global.set_initializer(&ty.const_int(u64::from(value), false));
    global.set_constant(true);
}

/// Emit an externally visible `u32[]`, retaining one zero sentinel for an
/// empty logical table because C cannot portably declare a zero-sized array.
fn u32_table<'ctx>(context: &'ctx Context, module: &Module<'ctx>, name: &str, values: &[u32]) {
    let ty = context.i32_type();
    let values = values
        .iter()
        .copied()
        .map(|value| ty.const_int(u64::from(value), false))
        .collect::<Vec<_>>();
    let fallback = [ty.const_zero()];
    let initializer = ty.const_array(if values.is_empty() {
        &fallback
    } else {
        &values
    });
    let global = module.add_global(initializer.get_type(), None, name);
    global.set_initializer(&initializer);
    global.set_constant(true);
}

/// Emit an externally visible `u8[]`, with the same empty-table convention as
/// [`u32_table`].
fn u8_table<'ctx>(context: &'ctx Context, module: &Module<'ctx>, name: &str, values: &[u8]) {
    let ty = context.i8_type();
    let values = values
        .iter()
        .copied()
        .map(|value| ty.const_int(u64::from(value), false))
        .collect::<Vec<_>>();
    let fallback = [ty.const_zero()];
    let initializer = ty.const_array(if values.is_empty() {
        &fallback
    } else {
        &values
    });
    let global = module.add_global(initializer.get_type(), None, name);
    global.set_initializer(&initializer);
    global.set_constant(true);
}

/// Emit a private NUL-terminated string and return its constant address.
fn private_string<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    name: &str,
    value: &str,
) -> PointerValue<'ctx> {
    let initializer = context.const_string(value.as_bytes(), true);
    let global = module.add_global(initializer.get_type(), None, name);
    global.set_initializer(&initializer);
    global.set_constant(true);
    global.set_linkage(Linkage::Private);
    global.as_pointer_value()
}

/// Emit externally visible `const char *const[]` test names. The logical
/// length is always `sx_test_count`; an empty design carries one null sentinel.
fn test_name_table<'ctx>(context: &'ctx Context, module: &Module<'ctx>, design: &Design) {
    let pointer = context.ptr_type(AddressSpace::default());
    let values = design
        .process_ir
        .tests
        .iter()
        .enumerate()
        .map(|(index, test)| {
            private_string(
                context,
                module,
                &format!("sx.test.name.{index}"),
                &test.qualified_name,
            )
        })
        .collect::<Vec<_>>();
    let fallback = [pointer.const_null()];
    let initializer = pointer.const_array(if values.is_empty() {
        &fallback
    } else {
        &values
    });
    let global = module.add_global(initializer.get_type(), None, "sx_test_names");
    global.set_initializer(&initializer);
    global.set_constant(true);
}

/// Compute which arena nodes the direct scalar emitter can lower. Values are
/// dependency ordered, so this stays iterative and cannot overflow the Rust
/// stack on a large generated expression graph.
fn supported_process_values(design: &Design) -> Vec<bool> {
    let mut supported = Vec::with_capacity(design.process_ir.values.len());
    let has = |supported: &[bool], id: ProcessValueId| {
        supported.get(id.0 as usize).copied().unwrap_or(false)
    };
    for value in &design.process_ir.values {
        let scalar_width = value
            .bit_width
            .is_some_and(|width| width != 0 && width <= super::emit::LLVM_MAX_INT_BITS);
        let shape = match &value.kind {
            ProcessValueKind::Number(_)
            | ProcessValueKind::BitString { .. }
            | ProcessValueKind::Char(_) => true,
            ProcessValueKind::Signal { signals, state } => {
                matches!(signals.as_slice(), [signal] if design.signals.get(signal.0 as usize).is_some())
                    && (!matches!(state, ProcessSignalState::Event) || value.bit_width == Some(1))
            }
            ProcessValueKind::BitSlice { base, high, low } => {
                has(&supported, *base)
                    && low <= high
                    && design
                        .process_ir
                        .values
                        .get(base.0 as usize)
                        .and_then(|value| value.bit_width)
                        .is_some_and(|width| *high < width)
            }
            ProcessValueKind::TableLookup { table, index } => {
                has(&supported, *index)
                    && design.lookup_tables.get(table.0).is_some_and(|table| {
                        !table.values.is_empty()
                            && table.values.len() <= u32::MAX as usize
                            && (1..=64).contains(&table.element_width)
                    })
            }
            ProcessValueKind::ForeignCall {
                arguments,
                float_arguments,
                integer_arguments,
                ..
            } => {
                arguments.len() == float_arguments.len()
                    && arguments.len() == integer_arguments.len()
                    && arguments.iter().all(|argument| has(&supported, *argument))
            }
            ProcessValueKind::Unary { operand, .. } => has(&supported, *operand),
            ProcessValueKind::Binary {
                operation,
                left,
                right,
            } => {
                !matches!(operation, ProcessBinaryOp::Custom(_))
                    && has(&supported, *left)
                    && has(&supported, *right)
            }
            ProcessValueKind::Select {
                condition,
                then_value,
                else_value,
            } => {
                has(&supported, *condition)
                    && has(&supported, *then_value)
                    && has(&supported, *else_value)
            }
            ProcessValueKind::Concat(parts) => {
                parts.iter().all(|part| has(&supported, *part))
                    && parts.iter().try_fold(0u32, |width, part| {
                        width.checked_add(design.process_ir.values.get(part.0 as usize)?.bit_width?)
                    }) == value.bit_width
            }
            ProcessValueKind::Suffixed { .. }
            | ProcessValueKind::String(_)
            | ProcessValueKind::Local { .. }
            | ProcessValueKind::Storage(_)
            | ProcessValueKind::Definition(_)
            | ProcessValueKind::Intrinsic(_)
            | ProcessValueKind::Field { .. }
            | ProcessValueKind::Attribute { .. }
            | ProcessValueKind::Index { .. }
            | ProcessValueKind::CheckedIndex { .. }
            | ProcessValueKind::Range { .. }
            | ProcessValueKind::MetaCompare { .. }
            | ProcessValueKind::Match { .. }
            | ProcessValueKind::Call { .. }
            | ProcessValueKind::Construct { .. }
            | ProcessValueKind::Array(_)
            | ProcessValueKind::Invalid => false,
        };
        supported.push(scalar_width && shape);
    }
    supported
}

/// Resolve a whole-scalar current-signal place to the staging helper emitted
/// for that signal. Projections and aggregate places remain unsupported until
/// their Process IR lowering is complete.
fn staged_signal_target(design: &Design, target: ProcessValueId) -> Option<SignalId> {
    let value = design.process_ir.values.get(target.0 as usize)?;
    let ProcessValueKind::Signal { signals, state } = &value.kind else {
        return None;
    };
    let [signal] = signals.as_slice() else {
        return None;
    };
    matches!(state, ProcessSignalState::Current)
        .then_some(*signal)
        .filter(|signal| design.signals.get(signal.0 as usize).is_some())
}

/// Whether a block is transactional for the currently implemented direct
/// subset. Unsupported blocks execute no foreign calls and publish no staged
/// writes before returning status 255.
fn block_is_supported(design: &Design, block: &siox::ir::ProcessBlock, values: &[bool]) -> bool {
    let value = |id: ProcessValueId| values.get(id.0 as usize).copied().unwrap_or(false);
    let instructions = block
        .instructions
        .iter()
        .all(|instruction| match instruction {
            siox::ir::ProcessInstruction::Assign {
                semantics: siox::ir::ProcessAssignment::StagedSignal,
                target,
                value: assigned,
                ..
            } => staged_signal_target(design, *target).is_some() && value(*assigned),
            _ => false,
        });
    let terminator = match &block.terminator {
        ProcessTerminator::Return { value: None, .. }
        | ProcessTerminator::Goto(_)
        | ProcessTerminator::Stop { .. }
        | ProcessTerminator::Finish { .. } => true,
        ProcessTerminator::Branch { condition, .. } => value(*condition),
        ProcessTerminator::Return { value: Some(_), .. }
        | ProcessTerminator::Match { .. }
        | ProcessTerminator::For { .. }
        | ProcessTerminator::Suspend { .. } => false,
    };
    instructions && terminator
}

/// Emit a process entry that resumes at any CFG block by its stable block ID.
///
/// Blocks containing only whole-scalar staged signal assignments execute
/// directly and publish into the object-owned pending state. Unsupported
/// executable nodes return [`PROCESS_UNSUPPORTED`] before a block performs any
/// calls or writes, making this a safe migration path rather than a second
/// partial semantic engine.
fn process_entry<'ctx>(
    context: &'ctx Context,
    module: &Module<'ctx>,
    design: &Design,
    process: &ProcessCfg,
) -> FunctionValue<'ctx> {
    let i8 = context.i8_type();
    let i32 = context.i32_type();
    let function = module.add_function(
        &format!("sx.process.{}", process.id.0),
        i8.fn_type(&[i32.into()], false),
        Some(Linkage::Internal),
    );
    let builder = context.create_builder();
    let dispatch = context.append_basic_block(function, "dispatch");
    let invalid = context.append_basic_block(function, "invalid");
    let blocks = process
        .blocks
        .iter()
        .map(|block| context.append_basic_block(function, &format!("bb{}", block.id.0)))
        .collect::<Vec<_>>();

    builder.position_at_end(dispatch);
    let resume = function
        .get_first_param()
        .expect("process entry has a resume block")
        .into_int_value();
    let cases = process
        .blocks
        .iter()
        .zip(&blocks)
        .map(|(block, llvm)| (i32.const_int(u64::from(block.id.0), false), *llvm))
        .collect::<Vec<_>>();
    builder.build_switch(resume, invalid, &cases).unwrap();

    builder.position_at_end(invalid);
    builder
        .build_return(Some(&i8.const_int(u64::from(PROCESS_UNSUPPORTED), false)))
        .unwrap();

    let supported_values = supported_process_values(design);
    for (block, llvm) in process.blocks.iter().zip(&blocks) {
        builder.position_at_end(*llvm);
        if !block_is_supported(design, block, &supported_values) {
            builder
                .build_return(Some(&i8.const_int(u64::from(PROCESS_UNSUPPORTED), false)))
                .unwrap();
            continue;
        }

        let mut cache = HashMap::new();
        let mut staged = Vec::with_capacity(block.instructions.len());
        let mut failed = false;
        for instruction in &block.instructions {
            let siox::ir::ProcessInstruction::Assign {
                semantics: siox::ir::ProcessAssignment::StagedSignal,
                target,
                value,
                ..
            } = instruction
            else {
                unreachable!("block support check admitted another instruction")
            };
            let signal = staged_signal_target(design, *target)
                .expect("block support check admitted a non-signal place");
            let width = design
                .signal_width(signal)
                .expect("validated signal target has a width");
            let Some(value) = process_value_at(
                context, module, &builder, design, *value, width, false, &mut cache,
            ) else {
                failed = true;
                break;
            };
            staged.push((signal, value));
        }
        let branch_condition = match &block.terminator {
            ProcessTerminator::Branch { condition, .. } => {
                process_value(context, module, &builder, design, *condition, &mut cache)
                    .and_then(|condition| as_condition(&builder, condition))
            }
            _ => None,
        };
        if failed
            || matches!(block.terminator, ProcessTerminator::Branch { .. })
                && branch_condition.is_none()
        {
            builder
                .build_return(Some(&i8.const_int(u64::from(PROCESS_UNSUPPORTED), false)))
                .unwrap();
            continue;
        }

        // All values and the terminator were emitted successfully before any
        // staged write becomes visible. Multiple writes to one target retain
        // source-order override because each helper replaces its pending slot.
        for (signal, value) in staged {
            let stage = module
                .get_function(&format!("sx.process.stage.{}", signal.0))
                .expect("Codegen emitted a stage helper for every signal");
            builder.build_call(stage, &[value.into()], "").unwrap();
        }

        match &block.terminator {
            ProcessTerminator::Return { value: None, .. } => {
                builder
                    .build_return(Some(&i8.const_int(u64::from(PROCESS_COMPLETED), false)))
                    .unwrap();
            }
            ProcessTerminator::Goto(target) => {
                builder
                    .build_unconditional_branch(blocks[target.0 as usize])
                    .unwrap();
            }
            ProcessTerminator::Stop { .. } => {
                builder
                    .build_return(Some(&i8.const_int(u64::from(PROCESS_STOPPED), false)))
                    .unwrap();
            }
            ProcessTerminator::Finish { .. } => {
                builder
                    .build_return(Some(&i8.const_int(u64::from(PROCESS_FINISHED), false)))
                    .unwrap();
            }
            ProcessTerminator::Branch {
                then_block,
                else_block,
                ..
            } => {
                builder
                    .build_conditional_branch(
                        branch_condition.expect("supported branch condition was emitted"),
                        blocks[then_block.0 as usize],
                        blocks[else_block.0 as usize],
                    )
                    .unwrap();
            }
            ProcessTerminator::Return { value: Some(_), .. }
            | ProcessTerminator::Match { .. }
            | ProcessTerminator::For { .. }
            | ProcessTerminator::Suspend { .. } => {
                builder
                    .build_return(Some(&i8.const_int(u64::from(PROCESS_UNSUPPORTED), false)))
                    .unwrap();
            }
        }
    }
    function
}

/// Emit the opaque function-pointer table consumed by the native scheduler.
fn process_entry_table<'ctx>(context: &'ctx Context, module: &Module<'ctx>, design: &Design) {
    let pointer = context.ptr_type(AddressSpace::default());
    let values = design
        .process_ir
        .processes
        .iter()
        .map(|process| {
            process_entry(context, module, design, process)
                .as_global_value()
                .as_pointer_value()
        })
        .collect::<Vec<_>>();
    let fallback = [pointer.const_null()];
    let initializer = pointer.const_array(if values.is_empty() {
        &fallback
    } else {
        &values
    });
    let global = module.add_global(initializer.get_type(), None, "sx_process_entries");
    global.set_initializer(&initializer);
    global.set_constant(true);
}

/// Materialize the runtime-facing test/process descriptor tables.
///
/// All lists use offset + flattened-value tables, avoiding generated symbols
/// whose shape changes per test. Process sensitivity kinds are encoded as
/// `0 = signal` and `1 = persistent storage`; process activation is `0 = once
/// at time zero`, `1 = reactive`. The counts make the sentinel elements of
/// logically empty arrays unobservable.
pub(super) fn emit_metadata<'ctx>(context: &'ctx Context, module: &Module<'ctx>, design: &Design) {
    let process_ir = &design.process_ir;
    u32_global(
        context,
        module,
        "sx_process_abi_version",
        PROCESS_ABI_VERSION,
    );
    u32_global(
        context,
        module,
        "sx_test_count",
        process_ir.tests.len() as u32,
    );
    u32_global(
        context,
        module,
        "sx_process_count",
        process_ir.processes.len() as u32,
    );
    test_name_table(context, module, design);
    process_entry_table(context, module, design);

    let test_roots = process_ir
        .tests
        .iter()
        .map(|test| test.root.0)
        .collect::<Vec<_>>();
    let mut test_process_offsets = Vec::with_capacity(process_ir.tests.len() + 1);
    let mut test_process_ids = Vec::new();
    for test in &process_ir.tests {
        test_process_offsets.push(test_process_ids.len() as u32);
        test_process_ids.extend(test.processes.iter().map(|process| process.0));
    }
    test_process_offsets.push(test_process_ids.len() as u32);
    u32_table(context, module, "sx_test_roots", &test_roots);
    u32_table(
        context,
        module,
        "sx_test_process_offsets",
        &test_process_offsets,
    );
    u32_table(context, module, "sx_test_process_ids", &test_process_ids);

    let roots = process_ir
        .processes
        .iter()
        .map(|process| process.root.0)
        .collect::<Vec<_>>();
    let owners = process_ir
        .processes
        .iter()
        .map(|process| process.owner.0)
        .collect::<Vec<_>>();
    let initial_blocks = process_ir
        .processes
        .iter()
        .map(|process| process.entry.0)
        .collect::<Vec<_>>();
    let activations = process_ir
        .processes
        .iter()
        .map(|process| match process.activation {
            ProcessActivation::TimeZero => 0,
            ProcessActivation::Reactive { .. } => 1,
        })
        .collect::<Vec<_>>();
    let mut sensitivity_offsets = Vec::with_capacity(process_ir.processes.len() + 1);
    let mut sensitivity_kinds = Vec::new();
    let mut sensitivity_ids = Vec::new();
    for process in &process_ir.processes {
        sensitivity_offsets.push(sensitivity_ids.len() as u32);
        if let ProcessActivation::Reactive { sensitivity } = &process.activation {
            for item in sensitivity {
                match item {
                    ProcessSensitivity::Signal(signal) => {
                        sensitivity_kinds.push(0);
                        sensitivity_ids.push(signal.0);
                    }
                    ProcessSensitivity::Storage(storage) => {
                        sensitivity_kinds.push(1);
                        sensitivity_ids.push(storage.0);
                    }
                }
            }
        }
    }
    sensitivity_offsets.push(sensitivity_ids.len() as u32);

    u32_table(context, module, "sx_process_roots", &roots);
    u32_table(context, module, "sx_process_owners", &owners);
    u32_table(
        context,
        module,
        "sx_process_initial_blocks",
        &initial_blocks,
    );
    u8_table(context, module, "sx_process_activations", &activations);
    u32_table(
        context,
        module,
        "sx_process_sensitivity_offsets",
        &sensitivity_offsets,
    );
    u8_table(
        context,
        module,
        "sx_process_sensitivity_kinds",
        &sensitivity_kinds,
    );
    u32_table(
        context,
        module,
        "sx_process_sensitivity_ids",
        &sensitivity_ids,
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use siox::diag::{FileId, Span};
    use siox::elab::InstanceId;
    use siox::ir::{
        ProcessBlock, ProcessBlockId, ProcessCfg, ProcessId, ProcessIr, ProcessSignalState,
        ProcessTerminator, ProcessTest, ProcessValue, ProcessValueId, ProcessValueKind, Signal,
        SignalId,
    };
    use siox::resolve::DefId;

    /// A source-less span for hand-built backend fixtures.
    fn span() -> Span {
        Span::new(FileId(0), 0..0)
    }

    /// The design object exports stable flattened descriptors without any
    /// generated C declaration list.
    #[test]
    fn emits_runtime_discovery_metadata() {
        let process_ir = ProcessIr {
            processes: vec![
                ProcessCfg {
                    id: ProcessId(0),
                    root: InstanceId(7),
                    owner: InstanceId(7),
                    label: Some("stimulus".into()),
                    span: span(),
                    activation: ProcessActivation::TimeZero,
                    entry: ProcessBlockId(0),
                    locals: vec![],
                    blocks: vec![ProcessBlock {
                        id: ProcessBlockId(0),
                        instructions: vec![],
                        terminator: ProcessTerminator::Return {
                            value: None,
                            span: None,
                        },
                    }],
                },
                ProcessCfg {
                    id: ProcessId(1),
                    root: InstanceId(7),
                    owner: InstanceId(8),
                    label: Some("dut.y".into()),
                    span: span(),
                    activation: ProcessActivation::Reactive {
                        sensitivity: vec![ProcessSensitivity::Signal(siox::ir::SignalId(0))],
                    },
                    entry: ProcessBlockId(0),
                    locals: vec![],
                    blocks: vec![ProcessBlock {
                        id: ProcessBlockId(0),
                        instructions: vec![],
                        terminator: ProcessTerminator::Return {
                            value: None,
                            span: None,
                        },
                    }],
                },
            ],
            tests: vec![ProcessTest {
                entity: DefId(11),
                root: InstanceId(7),
                qualified_name: "examples::Smoke".into(),
                span: span(),
                processes: vec![ProcessId(0), ProcessId(1)],
            }],
            storages: vec![],
            values: vec![],
        };
        let design = Design {
            signals: vec![siox::ir::Signal {
                path: "Smoke.dut.input".into(),
                declaration_span: span(),
                width: 1,
                real: false,
                integer: false,
                char: false,
                range: None,
                init: vec![0],
                enum_type: None,
            }],
            process_ir,
            ..Design::default()
        };
        let llvm = crate::llvm::emit_module_ir(&design).unwrap();
        assert!(llvm.contains("@sx_process_abi_version = constant i32 3"));
        assert!(llvm.contains("define i8 @sx_process_commit()"));
        assert!(llvm.contains("define i8 @sx_process_changed(i32"));
        assert!(llvm.contains("define internal void @sx.process.stage.0(i1"));
        assert!(llvm.contains("@sx_test_count = constant i32 1"));
        assert!(llvm.contains("@sx_process_count = constant i32 2"));
        assert!(
            llvm.contains("@sx.test.name.0 = private constant [16 x i8] c\"examples::Smoke\\00\"")
        );
        assert!(llvm.contains("@sx_test_process_offsets = constant [2 x i32] [i32 0, i32 2]"));
        assert!(llvm.contains("@sx_test_process_ids = constant [2 x i32] [i32 0, i32 1]"));
        assert!(llvm.contains(
            "@sx_process_entries = constant [2 x ptr] [ptr @sx.process.0, ptr @sx.process.1]"
        ));
        assert!(llvm.contains("@sx_process_initial_blocks = constant [2 x i32] zeroinitializer"));
        assert!(llvm.contains("@sx_process_activations = constant [2 x i8] c\"\\00\\01\""));
        assert!(llvm.contains(
            "@sx_process_sensitivity_offsets = constant [3 x i32] [i32 0, i32 0, i32 1]"
        ));
        assert!(llvm.contains("@sx_process_sensitivity_ids = constant [1 x i32] zeroinitializer"));
        assert!(llvm.contains("define internal i8 @sx.process.0(i32"));
        assert!(llvm.contains("define internal i8 @sx.process.1(i32"));
    }

    /// Empty logical descriptor tables still have legal storage for the C ABI,
    /// while their exported counts remain zero.
    #[test]
    fn empty_design_uses_unobservable_sentinels() {
        let llvm = crate::llvm::emit_module_ir(&Design::default()).unwrap();
        assert!(llvm.contains("@sx_test_count = constant i32 0"));
        assert!(llvm.contains("@sx_process_count = constant i32 0"));
        assert!(llvm.contains("@sx_test_names = constant [1 x ptr] zeroinitializer"));
        assert!(llvm.contains("@sx_process_entries = constant [1 x ptr] zeroinitializer"));
        assert!(llvm.contains("@sx_process_activations = constant [1 x i8] zeroinitializer"));
    }

    /// Resume dispatch preserves CFG block identity and emits the stable
    /// control-only status values before executable instruction coverage.
    #[test]
    fn process_entries_dispatch_control_only_cfgs() {
        let process_ir = ProcessIr {
            processes: vec![ProcessCfg {
                id: ProcessId(0),
                root: InstanceId(0),
                owner: InstanceId(0),
                label: Some("control".into()),
                span: span(),
                activation: ProcessActivation::TimeZero,
                entry: ProcessBlockId(0),
                locals: vec![],
                blocks: vec![
                    ProcessBlock {
                        id: ProcessBlockId(0),
                        instructions: vec![],
                        terminator: ProcessTerminator::Goto(ProcessBlockId(1)),
                    },
                    ProcessBlock {
                        id: ProcessBlockId(1),
                        instructions: vec![],
                        terminator: ProcessTerminator::Stop { span: span() },
                    },
                    ProcessBlock {
                        id: ProcessBlockId(2),
                        instructions: vec![],
                        terminator: ProcessTerminator::Finish { span: span() },
                    },
                    ProcessBlock {
                        id: ProcessBlockId(3),
                        instructions: vec![],
                        terminator: ProcessTerminator::Return {
                            value: Some(siox::ir::ProcessValueId(0)),
                            span: Some(span()),
                        },
                    },
                ],
            }],
            values: vec![siox::ir::ProcessValue {
                span: span(),
                ty: Some(siox::types::Ty::Integer),
                bit_width: Some(64),
                kind: siox::ir::ProcessValueKind::Number(siox::ir::ProcessNumber::Integer(vec![1])),
            }],
            ..ProcessIr::default()
        };
        let llvm = crate::llvm::emit_module_ir(&Design {
            process_ir,
            ..Design::default()
        })
        .unwrap();
        assert!(llvm.contains("i32 0, label %bb0"), "{llvm}");
        assert!(llvm.contains("i32 3, label %bb3"), "{llvm}");
        let body = |label: &str| {
            llvm.split_once(label)
                .map(|(_, rest)| rest.split_once("\n\n").map_or(rest, |(block, _)| block))
                .expect("emitted process block")
        };
        assert!(body("bb0:").contains("br label %bb1"), "{llvm}");
        assert!(body("bb1:").contains("ret i8 2"), "{llvm}");
        assert!(body("bb2:").contains("ret i8 3"), "{llvm}");
        assert!(body("bb3:").contains("ret i8 -1"), "{llvm}");
    }

    /// Direct branch lowering reconstructs current/old state from as many ABI
    /// words as required, combines it with event state, and branches on a
    /// selected high bit.
    #[test]
    fn process_branch_reads_exact_width_state_and_operations() {
        let process_ir = ProcessIr {
            processes: vec![ProcessCfg {
                id: ProcessId(0),
                root: InstanceId(0),
                owner: InstanceId(0),
                label: Some("wide-branch".into()),
                span: span(),
                activation: ProcessActivation::TimeZero,
                entry: ProcessBlockId(0),
                locals: vec![],
                blocks: vec![
                    ProcessBlock {
                        id: ProcessBlockId(0),
                        instructions: vec![],
                        terminator: ProcessTerminator::Branch {
                            condition: ProcessValueId(6),
                            then_block: ProcessBlockId(1),
                            else_block: ProcessBlockId(2),
                        },
                    },
                    ProcessBlock {
                        id: ProcessBlockId(1),
                        instructions: vec![],
                        terminator: ProcessTerminator::Stop { span: span() },
                    },
                    ProcessBlock {
                        id: ProcessBlockId(2),
                        instructions: vec![],
                        terminator: ProcessTerminator::Finish { span: span() },
                    },
                ],
            }],
            values: vec![
                ProcessValue {
                    span: span(),
                    ty: None,
                    bit_width: Some(65),
                    kind: ProcessValueKind::Signal {
                        signals: vec![SignalId(0)],
                        state: ProcessSignalState::Current,
                    },
                },
                ProcessValue {
                    span: span(),
                    ty: None,
                    bit_width: Some(65),
                    kind: ProcessValueKind::Signal {
                        signals: vec![SignalId(0)],
                        state: ProcessSignalState::Old,
                    },
                },
                ProcessValue {
                    span: span(),
                    ty: None,
                    bit_width: Some(1),
                    kind: ProcessValueKind::Signal {
                        signals: vec![SignalId(0)],
                        state: ProcessSignalState::Event,
                    },
                },
                ProcessValue {
                    span: span(),
                    ty: None,
                    bit_width: Some(1),
                    kind: ProcessValueKind::Binary {
                        operation: ProcessBinaryOp::Ne,
                        left: ProcessValueId(0),
                        right: ProcessValueId(1),
                    },
                },
                ProcessValue {
                    span: span(),
                    ty: None,
                    bit_width: Some(1),
                    kind: ProcessValueKind::BitSlice {
                        base: ProcessValueId(0),
                        high: 64,
                        low: 64,
                    },
                },
                ProcessValue {
                    span: span(),
                    ty: None,
                    bit_width: Some(1),
                    kind: ProcessValueKind::Binary {
                        operation: ProcessBinaryOp::And,
                        left: ProcessValueId(2),
                        right: ProcessValueId(3),
                    },
                },
                ProcessValue {
                    span: span(),
                    ty: None,
                    bit_width: Some(1),
                    kind: ProcessValueKind::Binary {
                        operation: ProcessBinaryOp::And,
                        left: ProcessValueId(4),
                        right: ProcessValueId(5),
                    },
                },
            ],
            ..ProcessIr::default()
        };
        let design = Design {
            signals: vec![Signal {
                path: "Wide.flag".into(),
                declaration_span: span(),
                width: 65,
                real: false,
                integer: false,
                char: false,
                range: None,
                init: vec![0, 0],
                enum_type: None,
            }],
            process_ir,
            ..Design::default()
        };
        let llvm = crate::llvm::emit_module_ir(&design).unwrap();
        assert!(
            llvm.contains("call i64 @sx_read_word(i32 0, i32 0)"),
            "{llvm}"
        );
        assert!(
            llvm.contains("call i64 @sx_read_word(i32 0, i32 1)"),
            "{llvm}"
        );
        assert!(
            llvm.contains("call i64 @sx.process.read.old(i32 0, i32 1)"),
            "{llvm}"
        );
        assert!(
            llvm.contains("call i64 @sx.process.read.event(i32 0, i32 0)"),
            "{llvm}"
        );
        assert!(llvm.contains("lshr i65"), "{llvm}");
        assert!(llvm.contains("icmp ne i65"), "{llvm}");
        assert!(llvm.contains("and i1"), "{llvm}");
        assert!(llvm.contains("br i1"), "{llvm}");
    }

    /// Oversized process-only values fail before asking LLVM to construct an
    /// unsupported integer type, even when no hardware signal has that width.
    #[test]
    fn unsupported_process_value_width_is_an_error_not_a_panic() {
        let process_ir = ProcessIr {
            values: vec![ProcessValue {
                span: span(),
                ty: None,
                bit_width: Some(crate::llvm::emit::LLVM_MAX_INT_BITS + 1),
                kind: ProcessValueKind::Number(siox::ir::ProcessNumber::Integer(vec![0])),
            }],
            ..ProcessIr::default()
        };
        let error = crate::llvm::emit_module_ir(&Design {
            process_ir,
            ..Design::default()
        })
        .unwrap_err();
        assert!(error.contains("process value 0"), "{error}");
        assert!(
            error.contains(&crate::llvm::emit::LLVM_MAX_INT_BITS.to_string()),
            "{error}"
        );
    }
}
